# Generated by Django 5.0.6 on 2024-05-13 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="Дата производства продукта",
            ),
        ),
    ]
