# Generated by Django 5.0.6 on 2024-05-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата создания (записи в БД)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата последнего изменения (записи в БД)",
            ),
        ),
    ]
